name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up node js
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Fresh start
      - run: npm install && npm ci
      - name: Run tests
      - run: npm run test
