name: Run Tests

on:
  pull_request: 
    branches: [main]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: npm ci
      - run: npm run test
